name: Build and static analysis

on:
  push:
    - "master"
  pull_request:
    types: [ opened, synchronize, reopened ]

jobs:

  build:
    runs-on: ubuntu-latest
    name: Build
    strategy:
      matrix:
        node-version: [ 14.x, 16.x, 17.x, 18.x ]    

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Setup Node Modules
        uses: bahmutov/npm-install@v1

      - name: Check Prettier (Format code)
      - run: npm run lint-prettier

      - name: Static Analysis
      - run: npm run static-analisys

      - name: Build TypeScript
      - run: npm run test:compile